version: '3'
services:
  yolov8_fastapi:
    build: .
    volumes:
      - .:/app
    ports:
      - "8008"
    networks:
      - dokploy_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.yolofastapi.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.yolofastapi.entrypoints=websecure"
      - "traefik.http.routers.yolofastapi.tls.certResolver=letsencrypt"
      - "traefik.http.services.yolofastapi.loadbalancer.server.port=3000"
    command: uvicorn main:app --host 0.0.0.0 --port 8008
networks:
  dokploy-network:
    external: true